
databaseA = ["Abacavir", "Abatacept", "Abciximab", "Abelcet", "Abilify", "Abreva", "Absorica", "Abstral", "Acamprosate", "Accolate", "Accretropin", "AccuNeb", "Accupril", "Accutane", "Aceon", "Aci-Jel", "Aciphex", "Aclovate", "Acrivastine", "Actemra", "Acthrel", "Acticin", "Actimmune", "Actisite", "Activase", "Activella", "Actonel", "Actoplus Met", "Actos", "Acular", "Acular LS", "Acuvail", "Acyclovir", "Adacel", "Adagen", "Adalat CC", "Adalimumab", "Adapalene", "Adcirca", "Adderall", "Adderall XR", "Adefovir Dipivoxil", "Adenoscan", "Adenosine", "Adipex-P", "Adoxa", "Adoxa CK", "Adoxa TT", "Adrenalin", "AdreView", "Advair Diskus", "Advair HFA", "Advate", "Advicor", "Aerospan HFA", "Afinitor", "Afluria", "Agalsidase Beta", "Aggrenox", "Akineton", "Alamast", "Albenza", "Aldactazide", "Aldactone", "Aldara", "Aldesleukin", "Aldomet", "Aldoril", "Aldurazyme", "Alefacept", "Alemtuzumab", "Alendronate", "Alesse", "Alfenta", "Alfentanil", "Alfuzosin", "Alglucosidase Alfa", "Alimta", "Alinia", "Alitretinoin", "Alkeran", "Allegra", "Allegra-D", "Allegra D 24 Hour", "Alli", "Allopurinol", "Almotriptan", "Alocril", "Aloprim", "Alora", "Alosetron", "Alphan"]

databaseB = ["Bacitracin", "Baclofen", "Bactrim", "Bactroban", "Balsalazide", "Banzel", "Baraclude", "Basiliximab", "Baycol", "Bayer", "BCG", "BCG Live", "Beclomethasone", "Beclovent", "Beconase", "Belsomra", "Belatacept", "Belimumab", "Belladonna", "Belladonna Alkaloids", "Belladonna Alkaloids", "Benadryl", "Benazepril", "Bendamustine", "Bendroflumethiazide", "Bentyl", "Benztropine", "Benzyl Alcohol Lotion", "Benzyl Alcohol", "Benzphetamine", "Benztropine", "Bepreve", "Bepridil", "Beractant", "Beta", "Bethanechol", "Betamethasone", "Betapace", "Betaseron", "Betaxolol", "Bethkis", "Bevacizumab", "Bexarotene", "Bexxar", "Bicalutamide", "Biaxin", "Bicillin", "Biltricide", "BiCNU", "Bimatoprost", "Biavax", "Bismuth", "Bismuth Subcitrate Potassium", "Bismuth Subsalicylate", "Bisoprolol", "Bivalirudin", "Bleomycin", "Blincyto", "Boniva", "Bontril", "Boostrix", "Bortezomib", "Bosentan", "Botox", "Botox Cosmetic", "Botulinum Toxin Type A", "Botulinum Toxin Type B", "Brevibloc", "Brevital Sodium", "Brimonidine", "Bromfenac", "Bromocriptine", "Brompheniramine", "Budesonide", "Bumetanide", "Buphenyl", "Bupivacaine", "Buprenorphine", "Bupropion", "Buspar", "Buspirone", "Busulfan", "Busulfex", "Butalbital", "Butorphanol", "Butoconazole", "Butrans", "Bystolic"]

databaseC = ["Cabergoline", "Caduet", "Caelyx", "Cafergot", "Caffeine", "Calciferol", "Calcitonin", "Calcitriol", "Calcium Acetate", "Calcium Carbonate", "Calcium Chloride", "Calcium Disodium Versenate", "Calcium Gluconate", "Calcium", "Calcium Gluceptate", "Calcium Gluconate", "Calcium Lactate", "Calcium Oyster Shell", "Calcium Phosphate", "Calcium Polycarbophil", "Calcium Salts", "Calcium Silicate", "Calcium Stearate", "Calcium Supplements", "Calcium with Vitamin D", "Calcium"]

databaseD = ["Dabigatran", "Dacarbazine", "Dacogen", "Dactinomycin", "Dactinomycin", "Dalfampridine", "Dalmane", "Danazol", "Dantrolene", "Dantrium", "Daraprim", "Darbepoetin Alfa", "Darifenacin", "Darunavir", "Darvocet", "Darvon", "Dasatinib", "Daunorubicin", "Daypro", "Daypro Alta", "DDAVP Nasal", "DDAVP", "Decadron", "Deferasirox", "Deferiprone", "Definity", "Deflazacort", "Degarelix", "Dehydroepiandr"]

databaseE = ["Ecallantide", "Ecotrin", "Eculizumab", "Edaravone", "Edetate Calcium Disodium", "Edetate Disodium", "Edex", "Edrophonium", "Efalizumab", "Efavirenz", "Effexor", "Effexor XR", "Eflornithine", "Elaprase", "Elavil", "Eldepryl", "Eletriptan", "Eligard", "Elimite", "Ellence", "Elmiron", "Elocon", "Eltrombopag", "Emadine", "Emcyt", "Emedastine", "Emend", "Emgel", "Emla", "Empagliflozin", "Empliciti", "Emtricitabine", "Emtriva", "Enablex", "Enalapril", "Enbrel", "Endocet", "Endometrin", "Endrate", "Enflurane", "Engerix-B", "Enoxacin", "Enoxaparin", "Enoxaparin", "Entacapone", "Entecavir", "Entereg", "Eovist", "Ephedrine", "Epiduo", "Epifoam", "Epinephrine", "Epipen", "Epipen Jr", "Epirubicin", "Epivir", "Epivir-HBV", "Eplerenone", "Epoetin Alfa", "Epoprostenol", "Eprosartan", "Eprosartan and Hydrochlorothiazide", "Eptifibatide", "Ergocalciferol", "Ergoloid Mesylates", "Ergomar", "Ergonovine", "Ergotamine", "Erlotinib", "Ertaczo", "Ertapenem", "Ery-Tab", "Eryc", "Erygel", "EryPed", "Erythrocin", "Erythrocin Stearate", "Erythromycin", "Erythromycin Base", "Erythromycin Ethylsuccinate", "Erythromycin Lactobionate", "Ery"]

databaseF = ["Fabrazyme", "Factor IX Complex", "Factor IX", "Factor VIIa", "Factor VIII", "Factor VIII Complex", "Factrel", "Famciclovir", "Famotidine", "Famvir", "Fansidar", "Fareston", "Faslodex", "Fastin", "Fazaclo", "Febuxostat", "Feldene", "Felodipine", "Femara", "Femhrt", "Femring", "Fenofibrate", "Fenofibric Acid", "Fenoglide", "Fenoldopam", "Fentanyl", "Fentora", "Feraheme", "Feridex I.V.", "Feriva", "Ferriprox", "Ferrous Fumarate", "Ferrous Gluconate", "Ferrous Sulfate", "Ferumoxytol", "Fesoterodine", "Fetzima", "Fexofenadine", "Fexofenadine and Pseudoephedrine", "FiberCon", "Fidaxomicin", "Filgrastim", "Finacea", "Finasteride", "Fioricet", "Fiorinal", "Fiorinal with Codeine", "Flagyl", "Flagyl ER", "Flavoxate", "Flecainide", "Flector", "Fleet Enema", "Fleet Phospho Soda", "Flexeril", "Flomax", "Flonase", "Florinef", "Flovent", "Flovent HFA", "Flovent Rotadisk", "Floxin", "Floxin Otic", "Fluconazole", "Flucytosine", "Fludara", "Fludarabine", "Fludarabine Phosphate", "Fludrocortisone", "Flumadine", "FluMist", "Fluocinolone", "Fluocinonide", "Fluorescein", "Fluoride", "Fluorometholone", "Fluoroplex", "Fluorouracil", "Fluoxetine", "Fluoxetine Capsules", "Fluoxetine Delayed-Release"]

databaseG = ["Gabapentin", "Gabitril", "Gadobenate Dimeglumine", "Gadobutrol", "Gadodiamide", "Gadofosveset Trisodium", "Gadopentetate Dimeglumine", "Gadoteridol", "Gadoversetamide", "Gadoxetate Disodium", "Galantamine", "Galsulfase", "Gamunex", "Ganciclovir", "Ganirelix", "Ganirelix Acetate", "Gantanol", "Gardasil", "Gatifloxacin", "Gatifloxacin Ophthalmic", "Gaviscon", "Gel-One", "Gelfoam", "Gemcitabine", "Gemfibrozil", "Gemifloxacin", "Gemtuzumab Ozogamicin", "Gengraf", "Genoptic", "Gentak", "Gentamicin", "Gentamicin Ophthalmic", "Gentamicin Sulfate", "Geodon", "Gianvi", "Gilenya", "Gilotrif", "Glatiramer", "Glatiramer Acetate", "Gleevec", "Glimepiride", "Glipizide", "Glipizide and Metformin", "Glucagon", "Glucophage", "Glucophage XR", "Glucotrol", "Glucotrol XL", "Glucovance", "Glumetza", "Glyburide", "Glyburide and Metformin", "Glycopyrrolate", "Glynase", "Glyset", "Glytone", "Glyxambi", "Golimumab", "Gonal-F", "Gonal-f RFF", "Gonal-f RFF Pen", "Gonitro", "Goserelin", "Granisetron", "Granisetron Transdermal", "Grastek", "Grifulvin V", "Griseofulvin", "Guanfacine", "Guanidine", "Guanidine Hydrochloride", "Guanfacine", "Gynazole", "Gyne-Lotrimin", "Gyne-Lotrimin 3 Day", "Gyne-Lotrim"]

databaseH = ["H.P. Acthar Gel", "Haemophilus b Conjugate Vaccine", "Halcinonide", "Haldol", "Haldol Decanoate", "Halobetasol", "Haloperidol", "Haloperidol Decanoate", "Halothane", "Havrix", "HCTZ", "Hecoria", "Hectorol", "Hemabate", "Hemangeol", "Hemocyte", "Hemofil M", "Hemofil-M", "Hemophilus b Conjugate Vaccine", "Hemorrhoidal HC", "Heparin Lock Flush", "Heparin Sodium", "Hepatitis A Vaccine", "Hepatitis B Immune Globulin", "Hepatitis B Vaccine", "Hepatitis B", "Hepatitis B Immune Globulin", "Hepatitis B Vaccine", "Hepatitis C", "Hepatitis C", "Hepatitis C Immune Globulin", "Hepatitis C Immune Globulin", "Hepatitis Immune Globulin", "Hepatitis Immune Globulin", "Hepflush-10", "Hepsera", "Herceptin"]

databaseI = ["Ibandronate", "Ibritumomab", "Ibuprofen", "Ibutilide", "Ibutilide Fumarate", "Ic-Green", "Icodextrin", "Idamycin", "Idamycin PFS", "Idarubicin", "Idarubicin Hydrochloride", "Idelalisib", "Idursulfase", "Ifex", "Ifosfamide", "Ifosfamide", "Iloperidone", "Iloprost", "Imatinib", "Imiglucerase", "Imipenem", "Imipramine", "Imiquimod", "Imitrex", "Imitrex Nasal", "Imitrex Statdose", "Immune Globulin", "Immune Globulin Intravenous", "Immune Globulin Subcutaneous", "Immune Globulin Intravenous and Subcutaneous", "Immune Globulin Intravenous and Subcutaneous", "Immune Globulin Subcutaneous", "Immune Globulin Intravenous", "Immune Globulin Intravenous and Subcutaneous", "Immune Globulin Intravenous and Subcutaneous", "Immune Globulin Subcutaneous", "Immune Globulin Intravenous", "Immune Globulin Intravenous and Subcutaneous", "Immune Globulin Intravenous and Subcutaneous", "Immune Globulin Subcutaneous", "Immune Globulin Intravenous", "Immune Globulin Intravenous and Subcutaneous", "Immune Globulin Intravenous and Subcutaneous", "Immune Globulin Subcutaneous", "Immune Globulin Intravenous", "Immune Globulin Intravenous and Subcutaneous", "Immune Globulin Intravenous and Subcutaneous", "Immune Globulin Subcutaneous", "Immune Globulin Intravenous", "Immune Globulin Intravenous and Subcutaneous", "Immune Globulin Intravenous and Subcutaneous", "Immune Globulin Subcutaneous", "Immune Globulin Intravenous", "Immune Globulin Intravenous and Subcutaneous", "Immune Globulin Intravenous and Subcutaneous", "Immune Globulin Subcutaneous", "Immune Globulin Intravenous", "Immune Globulin Intravenous and Subcutaneous", "Immune Globulin Intravenous and Subcutaneous"]

databaseJ = ["Jadenu", "Jalyn", "Janumet", "Janumet XR", "Januvia", "Jantoven", "Jardiance", "Jentadueto", "Je-Vax", "Jevtana", "Jinteli", "Jolivette", "Jublia", "Juvederm", "Juvederm Ultra", "Juvederm Ultra Plus"]

databaseK = ["K-Lor", "K-Tab", "Kadian", "Kaletra", "Kanamycin", "Kantrex", "Kapidex", "Kariva", "Kayexalate", "Keflex", "Kemadrin", "Kenalog", "Kepivance", "Keppra", "Keppra XR", "Kerlone", "Kerydin", "Ketalar", "Ketamine", "Ketamine Hydrochloride", "Ketek", "Ketoconazole", "Ketoprofen", "Ketorolac", "Ketorolac Ophthalmic", "Ketorolac Ophthalmic", "Ketorolac Tromethamine", "Ketotifen", "Ketotifen Ophthalmic", "Ketotifen Ophthalmic"]

databaseL = ["Labetalol", "Lac-Hydrin", "Lacrisert", "Lactated Ringers", "Lactulose", "Lamictal", "Lamictal ODT", "Lamictal XR", "Lamisil", "Lamivudine", "Lamivudine"]